---
- name: initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  debugger: on_failed
  args:
     chdir: $HOME
     creates: cluster_initialized.txt

- name: create .kube directory
  become: yes
  become_user: root
  file:
     path: $HOME/.kube
     state: directory
     mode: 0755

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes
    owner: root

- name: create pod network
  shell: |
      export kubever=$(kubectl version | base64 | tr -d '\n')
      kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: set join command
  set_fact:
   join_command: "{{ join_command_raw.stdout_lines[0] }}"