---
- hosts: all
  become: yes
  vars_files:
  - vars
  tasks:

  - name: Copy script mirrors.sh
    copy:
     src: scripts/mirrors.sh 
     dest: /tmp/mirrors.sh
     mode: 0755

  - name: Run script mirrors.sh 
    command: sh /tmp/mirrors.sh 

  - name: Upgrade RHEL Family OS packages
    yum:
      name: '*'
      state: latest
    register: result
    when: ansible_os_family == "RedHat"

  - debug:
    register: result
    verbosity: 3

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add IPs to /etc/hosts on master and workers
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

  - name: Add Docker repo
    get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
    become: yes
  
  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
 
  - name: Remove docker if installed from CentOS repo
    yum:
      name:
        - podman
        - container-tools
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
        - kubeadm
        - kubelet
      state: removed
  
  - name: Install Docker
    ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true
 
  - name: Restart docker
    service:
      name: docker
      daemon_reload: yes
      enabled: yes
      state: restarted 

  - name: Install kubernetes packages
    yum:
     name: [kubelet,kubeadm,kubectl]
     disable_excludes: kubernetes

  - name: Enable kubelet service
    ansible.builtin.service:
     name: kubelet
     enabled: yes  
  
  - name: Restart firewalld
    service:
      name: firewalld
      daemon_reload: yes
      enabled: yes
      state: restarted
      
  - name: Allow Network Ports in Firewalld
    ansible.posix.firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ master_ports if ('master-node' in group_names) else worker_ports }}"

  - name: Allow masquerading in Firewalld
    ansible.posix.firewalld:
      masquerade: "yes"
      state: enabled
      permanent: yes
      immediate: yes

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
